---
# Minecraft Server Provisioning and Management
- name: Minecraft Playbook - Deploy and manage Minecraft Server.
  hosts: all
  user: portaj # For the very first run, you will probably need to use root.
  sudo: yes

  vars:
    admin_user: portaj
    admin_group: wheel
    admin_key: /home/portaj/.ssh/id_rsa.pub

  roles:
  - common
  - { role: spigot, port: 25566 }
  - { role: bungee, port: 25565 }
