---
# Install a bungee server
- name: Bungee Server | {{ username }} should exist.
  user: name={{ username }}

- name: Bungee Server | Installation directory should exist.
  shell: mkdir -p {{ installation_directory }} owner={{ username }} group={{ username }} mode=0755
  args:
    creates: "{{ installation_directory }}"

- file: path={{ installation_directory }} owner={{ username }} group={{ username }} mode=0755

- name: Bungee Server | Download jar file.
  action: get_url url={{ jar_download }} dest={{ installation_directory }}bungee.jar

- file: path={{ installation_directory }}bungee.jar owner={{ username }} group={{ username }} mode=0755

- name: Bungee Server | start.sh should exist.
  template: src=start.sh dest={{ installation_directory }}start.sh owner={{ username }} group={{ username }} mode=0755

- name: Bungee Server | config.yml should exist.
  template: src=config.yml dest={{ installation_directory }}config.yml owner={{ username }} group={{ username }} mode=0655

- name: Bungee Server | systemd service file should exist.
  template: src=systemd.service dest=/etc/systemd/system/bungee-{{ port }}.service

- name: Bungee Server | firewalld open port
  command: firewall-cmd --zone=public --add-port={{ port }}/tcp --permanent

- name: Bungee Server | firewalld reload
  command: firewall-cmd --reload

- name: Bungee Server | systemd should reload
  command: systemctl daemon-reload

- name: Bungee Server | restart the service and make sure it is enabeld.
  action: service name=bungee-{{ port }} state=restarted enabled=yes
