---
# Install a spigot server
- name: Spigot Server | {{ username }} should exist.
  user: name={{ username }}

- name: Spigot Server | Installation directory should exist.
  shell: mkdir -p {{ installation_directory }} owner={{ username }} group={{ username }} mode=0755
  args:
    creates: "{{ installation_directory }}"

- file: path={{ installation_directory }} owner={{ username }} group={{ username }} mode=0755

- name: Spigot Server | Download jar file.
  action: get_url url={{ jar_download }} dest={{ installation_directory }}spigot.jar

- file: path={{ installation_directory }}spigot.jar owner={{ username }} group={{ username }} mode=0755

- name: Spigot Server | start.sh should exist.
  template: src=start.sh dest={{ installation_directory }}start.sh owner={{ username }} group={{ username }} mode=0755

- name: Spigot Server | agree to EULA.
  copy: src=eula.txt dest={{ installation_directory }}eula.txt owner={{ username }} group={{ username }} mode=0655

- name: Spigot Server | bukkit.yml should exist.
  template: src=bukkit.yml dest={{ installation_directory }}bukkit.yml owner={{ username }} group={{ username }} mode=0655

- name: Spigot Server | spigot.yml should exist.
  template: src=spigot.yml dest={{ installation_directory }}spigot.yml owner={{ username }} group={{ username }} mode=0655

- name: Spigot Server | server.properties should exist.
  template: src=server.properties dest={{ installation_directory }}server.properties owner={{ username }} group={{ username }} mode=0655

- name: Spigot Server | systemd service file should exist.
  template: src=systemd.service dest=/etc/systemd/system/spigot-{{ port }}.service

- name: Spigot Server | systemd should reload
  command: systemctl daemon-reload

- name: Spigot Server | restart the service and make sure it is enabeld.
  action: service name=spigot-{{ port }} state=restarted enabled=yes
